### ISSUE TITLE
CRAM support using htslib/Samtools

### ISSUE THREAD

**Issue by andyrimmer** [andyrimmer/Platypus#19]
Switch to newest Samtools version (or just use htslib directly), and test Platypus using CRAM and BAM
from the same dataset.

**Comment by ink1** [comment]
Hi guys, 
Your previous bundles were self-consistent whereas 0.8.1 is not because it needs htslib. I'm getting 

htslibWrapper.c:243:25: error: htslib/bgzf.h: No such file or directory
htslibWrapper.c:244:24: error: htslib/hts.h: No such file or directory
< ... >

Best
Igor
