### ISSUE TITLE
Platypus.py shebang line

### ISSUE THREAD

**Issue by AnthonyCorbett** [andyrimmer/Platypus#36]
Suggest using this shebang in Platypus.py driver file 

#!/usr/bin/env python

https://github.com/andyrimmer/Platypus/blob/1b7d5b5ada68d0df4f6212d097325bf5e6f18e68/src/python/Platypus.py

It's not dependent on particular installation. It will work for example with virtualenv setups and will allow python to be found by searching the PATH variable, thus allowing users, who are not root, to supply the python they'd like to use when running platypus.

**Comment by dancooke** [comment]
Done
