### ISSUE TITLE
highly inbred species

### ISSUE THREAD

**Issue by agolicz** [andyrimmer/Platypus#38]
Hi,

I work on highly inbred diploid plant species, in many plants we would expect >90-95% homozygosity. I have been testing Platypus and it seems to be faring quite well in this scenario. Do you think it is a legitimate application?

Agnieszka

**Comment by gerton** [comment]
Hi Agnieszka,

Yes — Platypus assumes diploid organisms; it will work fairly well in haploid species / chromosomes except for the occasional het call, but generally should not have difficulty with dealing with high levels of homozygosity.

Best wishes
Gerton
