### ISSUE TITLE
Variant calling on 454 RNAseq data

### ISSUE THREAD

**Issue by ulah** [andyrimmer/Platypus#41]
Hi,
I'm running platypus on some 454 RNAseq data I have. This however, required a minor modification of the read data and the cython source and I would like to know whether you think this will have any significant influence on the results (besides the normal problems arising with variant calling on RNAseq data...)
1) I read that platypus has problems with the long N's in the cigar from spliced alignments. I therefore used the GATK splitNcigar tools to get rid of those. Am I correct in assuming that platypus does not care about the vast amount of redundant read names and H's in the cigar that do result from this?!
2) Trying to run platypus on the split reads resulted in a couple of lines reading something like "... cannot fit into short ..." (doesn't remember the correct expression, but it was only a warning, so I ignored it initially) and although it continued to run and completed with "variant calling finished successfully", only a minor part of chr1 was processed. I therefore simply changed all short datatype's to int's in the cython source, recompiled and everything is running smoothly now. However, I don't really understand why the data is not fitting into short as the longest read I have is 600bp. Does platypus maybe use the cigar to calculate the read length and does it wrongly include the hard clipping operator (H) in this calculation? Btw: I'm curious to understand the problem as I will get some pacbio data in the near future :)
Best,
Urs

**Comment by dancooke** [comment]
You are correct in assuming Platypus does not care about redundant read names; the read names aren't looked at at-all. Hard clipped bases in the cigar string are skipped so this isn't an issue. As for the warning - I'd need some more details to diagnose what's happening here (e.g. what variables you changed).
