### ISSUE TITLE
Error: something is screwy

### ISSUE THREAD

**Issue by jwalabroad** [andyrimmer/Platypus#43]
Hello,
I am running Platypus 0.8.1 as follows:

python Platypus.py callVariants --bamFiles=tumor.bam,normal.bam --output=out.vcf --refFile=$REFHG19 --assemble=1

and am receiving errors like:
ERROR - Exception in region 1:0-100000. Error was Something is screwy here.

The program successfully completes, but the VCF file is empty. It only gives this error on some BAM files. Any suggestions on what could be causing this in my input data?

Best,
Jeremiah

**Comment by dancooke** [comment]
Hi Jeremiah,

I believe this exception can be thrown if there are multiple samples in each BAM files, but the total number of unique samples is equal to the number of BAM files (in which case one sample per BAM is assumed). Does this sound like it could be the case?

Best
Dan

On 13 Oct 2015, at 15:46, Jeremiah Wala <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I am running Platypus 0.8.1 as follows:

python Platypus.py callVariants --bamFiles=tumor.bam,normal.bam --output=out.vcf --refFile=$REFHG19 --assemble=1

and am receiving errors like:
ERROR - Exception in region 1:0-100000. Error was Something is screwy here.

The program successfully completes, but the VCF file is empty. It only gives this error on some BAM files. Any suggestions on what could be causing this in my input data?

Best,
Jeremiah

**Comment by jwalabroad** [comment]
Thanks Dan for the quick reply. Yes, that is the case with this BAM (was produced from a samtools merge). Is there any way to work around this without re-headering the BAM?

**Comment by jwalabroad** [comment]
Hi Dan,
Re-headering is easy enough for this actually, so I'm trying that. 
Best,
Jeremiah
