### ISSUE TITLE
Is there any way to set ploidy?

### ISSUE THREAD

**Issue by noporpoise** [andyrimmer/Platypus#45]
Is it possible to specify if the samples are haploid or diploid?  Or is Platypus only suitable for variant calling in diploid samples?

**Comment by dancooke** [comment]
No, Platypus has a fixed diploid model. You can of course give Platypus non-diploid samples and post-filter the calls, this should work pretty well for haploid data.

On 14 Dec 2015, at 23:25, Isaac Turner <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to specify if the samples are haploid or diploid? Or is Platypus only suitable for variant calling in diploid samples?
