### ISSUE TITLE
Best version to use?

### ISSUE THREAD

**Issue by jjfarrell** [andyrimmer/Platypus#46]
For a production run of Platypus, is it best to download the master from github and compile or use the tar.gz release 0.8.1.?

**Comment by andyrimmer** [comment]
I think using a numbered release (e.g. 0.8.1) is probably better, as it's
easier to refer back to
if you have any problems.

Kind regards,
Andy

On Fri, Feb 19, 2016 at 1:25 PM, jjfarrell <notifications@github.com> wrote:

> For a production run of Platypus, is it best to download the master from
> github and compile or use the tar.gz release 0.8.1.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andyrimmer/Platypus/issues/46>.
>

-- 
This email is sent on behalf of Genomics plc, a public limited company 
registered in England and Wales with registered number 8839972, VAT 
registered number 189 2635 65 and registered office at 24 Cornhill, London, 
EC3V 3ND, United Kingdom.
The contents of this e-mail and any attachments are confidential to the 
intended recipient. If you are not the intended recipient please do not use 
or publish its contents, contact Genomics plc immediately at 
info@genomicsplc.com <info@genomicsltd.com> then delete. You may not copy, 
forward, use or disclose the contents of this email to anybody else if you 
are not the intended recipient. Emails are not secure and may contain 
viruses.
