### ISSUE TITLE
Compiling Platypus on POWER7

### ISSUE THREAD

**Issue by IvantheDugtrio** [andyrimmer/Platypus#53]
I got the following error about lack of SSE2 and SSE3 options in GCC on my CentOS 7.2 POWER7 machine. What can I do to compile this without using those instruction sets?
[Platypus-compile-error.txt](https://github.com/andyrimmer/Platypus/files/330981/Platypus-compile-error.txt)

**Comment by gerton** [comment]
Hi Ivan,

I’m afraid Platypus needs SSE instructions to run.

Best wishes
Gerton
