### ISSUE TITLE
Increased number of variants with HapScore filter tag

### ISSUE THREAD

**Issue by NagaComBio** [andyrimmer/Platypus#56]
The number of variants with Hapscore filter tag (variants failed for Haploscore) have increased between the two versions I am using. The difference is huge compared to other filter parameters and it throws away a lot of good variants. 

Here is the count of filter tags for indels from an Exome called by Platypus_Version_0.7.4. For simplicity I removed the variants with multiple filter tags. 
```
   1671 alleleBias
   5375 badReads
    312 HapScore
   6262 MQ
  71988 PASS
   8368 Q20
   1511 QD
  11479 SC
      2 strandBias
```
And for the same sample using Platypus_Version_0.8.1
```
   1633 alleleBias
   6770 badReads
   6509 HapScore
   6030 MQ
  86891 PASS
   9519 Q20
   1598 QD
  11534 SC
      2 strandBias
```

And below are the filter tags from Platypus_Version_0.7.4 for variants with HapScore score tag in Platypus_Version_0.8.1. A major portion of them have passed all the filters. 

```
     49 alleleBias
     86 badReads
      6 badReads;alleleBias
      2 badReads;MQ
     18 badReads;QD
      1 badReads;QD;alleleBias
    272 HapScore
      3 HapScore;alleleBias
      8 HapScore;badReads
      2 HapScore;badReads;alleleBias
      3 HapScore;badReads;QD
      2 HapScore;badReads;QD;strandBias
      9 HapScore;MQ
     23 HapScore;QD
    126 MQ
      4 MQ;QD
   4414 PASS
    110 Q20
      1 Q20;badReads
      6 Q20;badReads;QD
      1 Q20;HapScore
      2 Q20;HapScore;QD
      3 Q20;MQ
      1 Q20;MQ;QD
     54 Q20;QD
    142 QD
      1 QD;alleleBias
      4 SC
      1 SC;alleleBias
      1 SC;badReads;QD

```

I checked with couple of samples, and all have the same issue. I couldn't find any information on this HapScore issue.

**Comment by dancooke** [comment]
May I assume a mistake was made given you have closed the issue?

**Comment by NagaComBio** [comment]
Yes, I realized the calling was done only for Indels in the older version, and SNP calling was also done with Master version. I guess, this increased the HapScore for indels surrounded by SNPs.
