### ISSUE TITLE
Merge multiple VCF files from multiple samples from Platypus

### ISSUE THREAD

**Issue by wenbostar** [andyrimmer/Platypus#69]
Hi,

I have ten samples and I used Platypus for variant calling for each sample separately. How can I merge these VCF files from Platypus?

Best regards!
Bo

**Comment by tdelhomme** [comment]
There are several different tools that can do that, for instance [bcftools](https://samtools.github.io/bcftools/bcftools.html), but maybe a first important step should be to normalize VCFs with [vt](https://genome.sph.umich.edu/wiki/Vt) to be sure the merge would be correct.

**Comment by wenbostar** [comment]
@tdelhomme , thanks for your suggestion. I will give a try.
