### ISSUE TITLE
Platypus Variant Calling, Exception OverflowError

### ISSUE THREAD

**Issue by TManning7** [andyrimmer/Platypus#82]
Hi there,

I'm trying to incorporate Platypus as part of my RNA-seq variant calling pipeline, after pre-processing with the Opossum tool (I tried to also use GATK pre-processing but couldn't get it working). I noticed that the variant caller ran unbelievably quickly compared to my other variant calling tools, and on inspecting the resulting error file (larger than the VCF), I saw lots of the above error, specifically:

"Exception OverflowError: 'value too large to convert to short' in 'htslibWrapper.ReadIterator.get' ignored"

I've tried googling for a solution but haven't been able to find one as of yet, hence this post. Any help would be appreciated.

Kind regards!

Tom

EDIT: Sorry, not sure how to delete this. I was using the GATK pre-processed data and not the Opossum pre-processed data. I would love to be able to use the GATK pre-processed BAMs too for comparison, but that's a different question to ask.

**Comment by williamkramer1** [comment]
Hello, was this resolved? I am having the same issue

**Comment by Wulei26** [comment]
hello，I also have the same problem ,How can I fix this?
